print 'This file must be run as "python -m alacrity.spritesheets.gen_hero_dropdown"'

import os
import time
import alacrity.spritesheets.dota_file_parser as dota_file_parser
from alacrity.parsers.utils import HeroNameDict

spritesheets_dir = os.path.dirname(os.path.realpath(__file__))
heroes_file = os.path.join(spritesheets_dir, 'npc_heroes.txt')
out_path = os.path.join(spritesheets_dir, '_hero_dropdown.html.erb')

# data from dota2 files: resource/flash3/images/heroes
print 'Expecting hero icons to be in "heroes" (e.g. "heroes/antimage.png")'
print 'Expecting hero data to be in current folder (e.g. "npc_heroes.txt")'
hero_data = dota_file_parser.parse(heroes_file)

hero_list = {k:v['HeroID'] for k,v in hero_data['DOTAHeroes'].iteritems() \
            if k.startswith('npc_dota_hero') and
                'HeroID' in v}

outer_top = """<%# Generated by alacrity.spritesheets.gen_hero_dropdown.py - {} %>
<select name="hero" class="form-control">
  <option value="all" selected>All Heroes</option>
""".format(time.ctime())
outer_bot = '</select>'
inner_tmpl = '  <option value="{id}">{name}</option>\n'

with open(out_path, 'wb') as f:
    f.write(outer_top)
    heroes = [(n,HeroNameDict[n]['localized_name']) for n,i in hero_list.iteritems()]
    # sort list by hero name
    for n,name in sorted(heroes, key=lambda x: x[1]):
        # skip heroes in game files that aren't in name dictionary
        try:
            f.write(inner_tmpl.format(id=n, name=name))
        except KeyError as e:
            print e
            pass
    f.write(outer_bot)
